### ISSUE TITLE
:tag_name locator should accept Regexp as a value

### ISSUE THREAD

**Issue by jarmo** [watir/watir-classic#65]
The code below does not work:

``` ruby
browser.element(:tag_name => /input/).should exist
```

This error will be thrown:

```
NoMethodError:
  undefined method `value' for /title/:Regexp
# ./lib/watir-classic/locator.rb:138:in `method_missing'
# ./lib/watir-classic/locator.rb:138:in `each_element'
# ./lib/watir-classic/locator.rb:22:in `block in each'
# ./lib/watir-classic/locator.rb:21:in `each'
# ./lib/watir-classic/locator.rb:21:in `each'
# ./lib/watir-classic/locator.rb:149:in `locate'
# ./lib/watir-classic/element.rb:308:in `locate'
...
```

Issue extracted from #62.

**Comment by jarmo** [comment]
Closing this due to inactivity.
