### ISSUE TITLE
Ruby 2.3.0 x64 --- Watir Exec format error (LoadError) --- in Fiddle line 47

### ISSUE THREAD

**Issue by ZigmaZigmax** [watir/watir-classic#81]
require 'watir-classic'

b = Watir::Browser.new :ie
b.goto "https://www.google.com/search?q=searching"

I am still getting this error

C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in `initialize': Exec format error (LoadError)
    from C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in`new'
    from C:/ruby23x64/lib/ruby/2.3.0/fiddle.rb:47:in `dlopen'
    from C:/ruby23x64/lib/ruby/2.3.0/Win32API.rb:15:in`initialize'
    from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:15:in `new'
    from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:15:in`module:Win32'
    from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:11:in `<module:Watir>'
    from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic/win32.rb:9:in`<top (required)>'
    from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from C:/ruby23x64/lib/ruby/gems/2.3.0/gems/watir-classic-4.3.0/lib/watir-classic.rb:32:in `<top (required)>'
    from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in`require'
    from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from C:/ruby23x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in`require'
    from C:/cygwin64/home/asdi/workspace/test1/test.rb:1:in `<main>'

**Comment by jkotests** [comment]
Sorry, at the moment, Watir-Classic only supports up to Ruby 2.2.

Note that if you are just starting out with Watir, you should switch to Watir-Webdriver instead. Support for Watir-Classic is quite minimal.

**Comment by jarmo** [comment]
Closing this due to inactivity.
